import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import ParticlesBackground from "../components/ParticlesBackground";
import Footer from "../components/Footer.jsx";
import { Providers } from "./providers";
import { ThemeCharacters } from "@/components/ui/theme-characters";
import { useTheme } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased flex flex-col min-h-screen">
        <Providers>
          <ThemeCharacters />
          <ParticlesBackground />
          <ErrorReporter />
          <Script
            src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
            strategy="afterInteractive"
            data-target-origin="*"
            data-message-type="ROUTE_CHANGE"
            data-include-search-params="true"
            data-only-in-iframe="true"
            data-debug="true"
            data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
          />
          <main className="flex-1 relative z-20 px-4 md:px-8">{children}</main>
          <Footer />
          <VisualEditsMessenger />
        </Providers>
      </body>
    </html>
  );
}
